const _ = require('lodash');

const regionListTh = [
  { label: 'ภาคกลาง', value: 1 },
  { label: 'ภาคเหนือ', value: 2 },
  { label: 'ภาคใต้', value: 3 },
  { label: 'ภาคตะวันออก', value: 4 },
  { label: 'ภาคตะวันตก', value: 5 },
  { label: 'ภาคตะวันออกเฉียงเหนือ', value: 6 },
  { label: 'ทั่วประเทศ', value: 7 },
];

const data = [
  { label: 'Bangkok', value: 1, region: 1 },
  { label: 'Samut Prakarn', value: 57, region: 4 },
  { label: 'Nonthaburi', value: 36, region: 1 },
  { label: 'Pathum Thani', value: 37, region: 1 },
  { label: 'Phra Nakhon Si Ayutthaya', value: 46, region: 1 },
  { label: 'Ang Thong', value: 3, region: 1 },
  { label: 'Lop Buri', value: 22, region: 1 },
  { label: 'Sing Buri', value: 62, region: 1 },
  { label: 'Chai Nat', value: 7, region: 1 },
  { label: 'Saraburi', value: 60, region: 1 },
  { label: 'Nakhon Nayok', value: 26, region: 1 },
  { label: 'Chon Buri', value: 12, region: 4 },
  { label: 'Rayong', value: 53, region: 4 },
  { label: 'Chanthaburi', value: 9, region: 4 },
  { label: 'Trat', value: 71, region: 4 },
  { label: 'Chachoengsao', value: 6, region: 4 },
  { label: 'Prachin Buri', value: 49, region: 4 },
  { label: 'Sa kaeo', value: 55, region: 4 },
  { label: 'Nakhon Ratchasima', value: 29, region: 6 },
  { label: 'Buri Ram', value: 5, region: 6 },
  { label: 'Surin', value: 68, region: 6 },
  { label: 'Si Sa Ket', value: 63, region: 6 },
  { label: 'Ubon Ratchathani', value: 72, region: 6 },
  { label: 'Yasothon', value: 77, region: 6 },
  { label: 'Chaiyaphum', value: 8, region: 6 },
  { label: 'Amnat Charoen', value: 2, region: 6 },
  { label: 'Bueng Kan', value: 4, region: 6 },
  { label: 'Nong Bua Lam Phu', value: 34, region: 6 },
  { label: 'Khon Kaen', value: 17, region: 6 },
  { label: 'Udon Thani', value: 73, region: 6 },
  { label: 'Loei', value: 21, region: 6 },
  { label: 'Nong Khai', value: 35, region: 6 },
  { label: 'Maha Sarakham', value: 24, region: 6 },
  { label: 'Roi Et', value: 54, region: 6 },
  { label: 'Kalasin', value: 14, region: 6 },
  { label: 'Sakon Nakhon', value: 56, region: 6 },
  { label: 'Nakhon Phanom', value: 28, region: 6 },
  { label: 'Mukdahan', value: 25, region: 6 },
  { label: 'Chiang Mai', value: 10, region: 2 },
  { label: 'Lamphun', value: 20, region: 2 },
  { label: 'Lampang', value: 19, region: 2 },
  { label: 'Uttaradit', value: 75, region: 2 },
  { label: 'Phrae', value: 47, region: 2 },
  { label: 'Nan', value: 32, region: 2 },
  { label: 'Phayao', value: 41, region: 2 },
  { label: 'Chiang Rai', value: 11, region: 2 },
  { label: 'Mae Hong Son', value: 23, region: 2 },
  { label: 'Nakhon Sawan', value: 30, region: 1 },
  { label: 'Uthai Thani', value: 74, region: 1 },
  { label: 'Kamphaeng Phet', value: 15, region: 1 },
  { label: 'Tak', value: 69, region: 5 },
  { label: 'Sukhothai', value: 65, region: 1 },
  { label: 'Phitsanulok', value: 45, region: 1 },
  { label: 'Phichit', value: 44, region: 1 },
  { label: 'Phetchabun', value: 42, region: 1 },
  { label: 'Ratchaburi', value: 52, region: 5 },
  { label: 'Kanchanaburi', value: 16, region: 5 },
  { label: 'Suphan Buri', value: 66, region: 1 },
  { label: 'Nakhon Pathom', value: 27, region: 1 },
  { label: 'Samut Sakhon', value: 58, region: 1 },
  { label: 'Samut Songkhram', value: 59, region: 1 },
  { label: 'Phetchaburi', value: 43, region: 5 },
  { label: 'Prachuap Khiri Khan', value: 50, region: 5 },
  { label: 'Nakhon Si Thammarat', value: 31, region: 3 },
  { label: 'Krabi', value: 18, region: 3 },
  { label: 'Phang-nga', value: 39, region: 3 },
  { label: 'Phuket', value: 48, region: 3 },
  { label: 'Surat Thani', value: 67, region: 3 },
  { label: 'Ranong', value: 51, region: 3 },
  { label: 'Chumphon', value: 13, region: 3 },
  { label: 'Songkhla', value: 64, region: 3 },
  { label: 'Satun', value: 61, region: 3 },
  { label: 'Trang', value: 70, region: 3 },
  { label: 'Phatthalung', value: 40, region: 3 },
  { label: 'Pattani', value: 38, region: 3 },
  { label: 'Yala', value: 76, region: 3 },
  { label: 'Narathiwat', value: 33, region: 3 },
];

// const dataSort = data.sort((a, b) => (a.region > b.region ? 1 : a.region > b.region ? -1 : 0));

const dataSort = _.sortBy(data, 'region');

console.log('dataSort :>> ', dataSort);
